### ISSUE TITLE
Contact mail on project's landing page is broken

### ISSUE THREAD

**Issue by javiergarea** [FreeProving/guidelines#7]
Sending an email to the addresses specified in https://freeproving.github.io/project-landing-page/ returns `Recipient address rejected: undeliverable address: Address lookup failed`. Is there any other email address to reach out to about the project?

**Comment by ichistmeinname** [comment]
Thanks for letting us know about this issue. As usual in the academic world, contracts end and mail addresses get deactivated. We‘ll add contact information to the README of the compiler repo.

**Comment by ichistmeinname** [comment]
I added contact addresses [here](https://github.com/FreeProving/free-compiler).
